name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      DB_CONNECTION: mysql
      DB_DATABASE: testing
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      APP_ENV: testing
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
          coverage: xdebug
      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress
      - name: Run Pint (Laravel linter)
        run: |
          ./vendor/bin/pint --test
      - name: Run Larastan
        run: |
          ./vendor/bin/phpstan analyse --memory-limit=1G
      - name: Prepare Laravel Application
        run: |
          cp .env.example .env || true
          php artisan key:generate
          php artisan migrate --force
      - name: Run Tests
        run: |
          ./vendor/bin/phpunit
